version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      #      - "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}


  web:
    build: .
    command: sh -c "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  celery-worker:
    build: .
    command: celery -A core worker -l info
    depends_on:
      - web

  celery-beat:
    build: .
    command: celery -A core beat -l info
    depends_on:
      web:
        condition: service_started


volumes:
  postgres:


