version: "3.9"

services:
  web:
    build: .
    command: sh -c "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASS}
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_PORT: ${DB_PORT}
#      POSTGRES_HOST: ${DB_HOST}

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  celery-worker:
    build: .
    command: celery -A core worker -l info
    depends_on:
      - code

  celery-beat:
    build: .
    command: celery -A core beat -l info
    depends_on:
      code:
        condition: service_started


volumes:
  postgres_data:


