# Generated by Django 5.0.1 on 2024-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_profile", "0002_bookingmodel_interesting_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingmodel",
            name="interesting_car",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
