# Generated by Django 5.0.1 on 2024-01-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bodytype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('power', models.FloatField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autosalon.bodytype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autosalon.color')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autosalon.country')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autosalon.mark')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_autosalon.transmission')),
            ],
        ),
    ]
