# Generated by Django 5.0.1 on 2024-01-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autosalon', '0002_mark_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='makr_image/'),
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photo')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_autosalon.auto')),
            ],
        ),
    ]
