# Generated by Django 5.0.1 on 2024-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_autosalon", "0006_mark_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auto",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
