# Generated by Django 5.0.1 on 2024-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_autosalon", "0007_auto_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="model",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
