# Generated by Django 5.0.1 on 2024-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
