# Generated by Django 5.0.1 on 2024-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_managers', '0002_manager_manager_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_photo',
            field=models.ImageField(blank=True, null=True, upload_to='manager_photo/'),
        ),
    ]
